### ISSUE TITLE
本地事务有验证过吗?

### ISSUE THREAD

**Issue by chenrenfei** [dynamic-datasource/dynamic-datasource-samples#5]
使用 @DSTransactional 情况下，你将druid数据源设置为defaultAutoCommit=false 事务是没有提交的

**Comment by huayanYu** [comment]
你这种场景没试过。 你有什么场景一定要设置这个值？

**Comment by chenrenfei** [comment]
我已经试过了，autocommit=true 自动就提交了，尤其是批量操作，回滚也没有用的

**Comment by chenrenfei** [comment]
用jta 模式下是可以的

**Comment by huayanYu** [comment]
就用默认的啊，不要去手动设置啊。  本地事务至少有几十家企业在用了。
可能你的配置和场景特殊，如有需要请进群详聊。

**Comment by chenrenfei** [comment]
QQ群吗？给一个群号码，我估计是获得connection 的地方需要按照dynamic的方式从ThreadLocal中获取和释放
```java

public class DefaultConnectionFactory implements ConnectionFactory {
	/**
	 * 此处是sqltoy跟数据源唯一有关联的地方，其他地方只负责将dataSource传递过来
	 */
	@Override
	public Connection getConnection(DataSource dataSource) {
		return DataSourceUtils.getConnection(dataSource);
	}

	/**
	 * sqltoy只是获得connection进行sql处理，conn的关闭和commit都
	 */
	@Override
	public void releaseConnection(Connection conn, DataSource dataSource) {
		DataSourceUtils.releaseConnection(conn, dataSource);
	}

}
```

**Comment by huayanYu** [comment]
@chenrenfei org.springframework.jdbc.datasource.DataSourceUtils是在spring事务下用的，它会复用连接。

mybatis大概org.mybatis.spring.SqlSessionUtils 161  ，它大概意思是判断是不是在事务中，在事务中会复用sqlSession。

可能你需要抽象一层， 不能直接判断调用org.springframework.jdbc.datasource.DataSourceUtils.getConnection(dataSource)

**Comment by chenrenfei** [comment]
是的，我扩展了一下，已经可以运行并得到正确结果了，赞！
下面是我的代码，帮忙看一下获得当前连接的方式是否正确? 另外connection 跟spring不同的就是无需做释放了

```java
@Override
	public Connection getConnection(DataSource dataSource) {
		String dsKey = DynamicDataSourceContextHolder.peek();
		ConnectionProxy conn = com.baomidou.dynamic.datasource.tx.ConnectionFactory.getConnection(dsKey);
		if (conn == null) {
			try {
				Connection realConn = dataSource.getConnection();
				conn = new ConnectionProxy(realConn, dsKey);
				com.baomidou.dynamic.datasource.tx.ConnectionFactory.putConnection(dsKey, conn);
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		return conn.getConnection();
	}

	@Override
	public void releaseConnection(Connection conn, DataSource datasource) {

	}
```

**Comment by huayanYu** [comment]
@chenrenfei  你这样不就和多数据源又强行绑定了么？0 0
没有用多数据源的不就报错了么。
感觉你需要参考mybatis那样，抽象出一层判断当前是否在事务中。
mybatis分为两个包，mybatis和mybatis-spring。
mybatis可以在没有spring的环境下独立运行，用的DefaultSqlSession。
在spring环境下，会用到sqlSessionTemplate如果是在事务中，只会生成一个SqlSession，如果不在事务中每次请求都会生成一个SqlSession。

**Comment by chenrenfei** [comment]
这个是由开发根据自己情况进行的扩展，sqltoy默认是以spring的实现，没有严格绑定。
sqltoy目前依赖spring，还没有想好是否要支持非spring

非常感谢！
